import { useState } from 'preact/hooks';
import { trpc } from '../trpc';
import { RefreshButton, FilterField } from '../components/log-controls';

const RANGE_OPTIONS = [
  { value: 'all', label: 'All time' },
  { value: '1',   label: 'Today' },
  { value: '7',   label: 'Last 7 days' },
  { value: '30',  label: 'Last 30 days' },
  { value: '90',  label: 'Last 90 days' },
] as const;

type RangeValue = typeof RANGE_OPTIONS[number]['value'];

function rangeToSinceDays(r: RangeValue): number | undefined {
  return r === 'all' ? undefined : Number(r);
}

function formatInt(n: number): string {
  return n.toLocaleString();
}

function formatUsd(n: number): string {
  if (n === 0) return '$0';
  if (n >= 1) return `$${n.toFixed(2)}`;
  return `$${n.toFixed(4)}`;
}

export function TokensView({ alias }: { alias: string }) {
  const [range, setRange] = useState<RangeValue>('30');
  const sinceDays = rangeToSinceDays(range);

  const summary = trpc.tokens.summary.useQuery({ alias, sinceDays });
  const byDay = trpc.tokens.byDay.useQuery({ alias, sinceDays });
  const byConv = trpc.tokens.byConversation.useQuery({ alias, sinceDays, limit: 200 });

  const refetchAll = () => { summary.refetch(); byDay.refetch(); byConv.refetch(); };
  const isFetching = summary.isFetching || byDay.isFetching || byConv.isFetching;

  const t = summary.data?.totals;

  return (
    <div class="space-y-6">
      <div class="flex items-end justify-between gap-4">
        <p class="text-xs text-gray-500 flex-1 min-w-0 max-w-2xl">
          Cost is reported by the Claude SDK at Anthropic API list prices — it is
          informational only, not your actual bill if you use a Claude
          subscription, Bedrock, Vertex, or negotiated rates.
        </p>
        <div class="flex items-end gap-3 shrink-0">
          <FilterField
            label="Range"
            value={range}
            options={RANGE_OPTIONS.map((o) => ({ value: o.value, label: o.label }))}
            onChange={(v) => setRange(v as RangeValue)}
            width="w-40"
          />
          <RefreshButton onClick={refetchAll} disabled={isFetching} />
        </div>
      </div>

      <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        <SummaryCard
          label="Input"
          value={t ? formatInt(t.input_tokens) : '—'}
          hint="Sent to the model."
        />
        <SummaryCard
          label="Output"
          value={t ? formatInt(t.output_tokens) : '—'}
          hint="Generated by the model. ~5× pricier."
        />
        <SummaryCard
          label="Cache read"
          value={t ? formatInt(t.cache_read_input_tokens) : '—'}
          hint="Reused from cache. ~10× cheaper."
        />
        <SummaryCard
          label="Cache creation"
          value={t ? formatInt(t.cache_creation_input_tokens) : '—'}
          hint="Stored for reuse. Small premium."
        />
        <SummaryCard
          label="Cost (list price)"
          value={t ? formatUsd(t.cost_usd) : '—'}
          hint="At Anthropic API list prices."
        />
      </div>

      <Section title="By day">
        {byDay.isLoading && <p class="text-gray-500 text-sm">Loading…</p>}
        {!byDay.isLoading && (!byDay.data || byDay.data.length === 0) && (
          <p class="text-gray-500 text-sm">No token usage in this range.</p>
        )}
        {byDay.data && byDay.data.length > 0 && (
          <div class="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden">
            <table class="w-full text-sm">
              <thead>
                <tr class="text-left text-gray-500 border-b border-gray-800">
                  <th class="px-4 py-3 font-medium">Date</th>
                  <th class="px-4 py-3 font-medium text-right">Input</th>
                  <th class="px-4 py-3 font-medium text-right">Output</th>
                  <th class="px-4 py-3 font-medium text-right">Cache read</th>
                  <th class="px-4 py-3 font-medium text-right">Cache creation</th>
                  <th class="px-4 py-3 font-medium text-right">Turns</th>
                  <th class="px-4 py-3 font-medium text-right">Cost (list)</th>
                </tr>
              </thead>
              <tbody>
                {byDay.data.map((d) => (
                  <tr key={d.date} class="border-t border-gray-800/50">
                    <td class="px-4 py-3 text-gray-300">{d.date}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(d.input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(d.output_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(d.cache_read_input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(d.cache_creation_input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(d.result_count)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatUsd(d.cost_usd)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Section>

      <Section title="By conversation">
        {byConv.isLoading && <p class="text-gray-500 text-sm">Loading…</p>}
        {!byConv.isLoading && (!byConv.data || byConv.data.length === 0) && (
          <p class="text-gray-500 text-sm">No conversation usage in this range.</p>
        )}
        {byConv.data && byConv.data.length > 0 && (
          <div class="bg-gray-900 border border-gray-800 rounded-lg overflow-x-auto">
            <table class="w-full min-w-max text-sm">
              <thead>
                <tr class="text-left text-gray-500 border-b border-gray-800">
                  <th class="px-4 py-3 font-medium">Conversation</th>
                  <th class="px-4 py-3 font-medium">Channel</th>
                  <th class="px-4 py-3 font-medium">Phase</th>
                  <th class="px-4 py-3 font-medium">Model</th>
                  <th class="px-4 py-3 font-medium text-right">Input</th>
                  <th class="px-4 py-3 font-medium text-right">Output</th>
                  <th class="px-4 py-3 font-medium text-right">Cache read</th>
                  <th class="px-4 py-3 font-medium text-right">Cache creation</th>
                  <th class="px-4 py-3 font-medium text-right">Turns</th>
                  <th class="px-4 py-3 font-medium text-right">Cost (list)</th>
                </tr>
              </thead>
              <tbody>
                {byConv.data.map((row) => (
                  <tr key={`${row.conversation_id}|${row.channel}|${row.phase}|${row.model}`} class="border-t border-gray-800/50">
                    <td class="px-4 py-3 text-gray-300 font-mono text-xs" title={row.conversation_id}>
                      {truncate(row.conversation_id, 28)}
                    </td>
                    <td class="px-4 py-3 text-gray-400">{row.channel}</td>
                    <td class="px-4 py-3 text-gray-400">{row.phase}</td>
                    <td class="px-4 py-3 text-gray-400 text-xs">{row.model}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(row.input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(row.output_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(row.cache_read_input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(row.cache_creation_input_tokens)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatInt(row.result_count)}</td>
                    <td class="px-4 py-3 text-gray-400 text-right tabular-nums">{formatUsd(row.cost_usd)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Section>
    </div>
  );
}

function SummaryCard({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div class="bg-gray-900 border border-gray-800 rounded-lg px-4 py-3 flex flex-col gap-1">
      <div class="text-xs font-medium text-gray-500 uppercase tracking-wider">{label}</div>
      <div class="text-lg text-white tabular-nums">{value}</div>
      <div class="text-xs text-gray-500 leading-snug">{hint}</div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: preact.ComponentChildren }) {
  return (
    <div class="space-y-2">
      <h3 class="text-sm font-medium text-gray-400">{title}</h3>
      {children}
    </div>
  );
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`;
}
